/**
 * Service Terms Page
 * Url: /service-terms
 */

import React from 'react'
import { Helmet } from 'react-helmet'
import {
    IonContent, IonLabel, IonRow
} from '@ionic/react'

/* css */
import '../HomePage.scss'

/* Components */
import PageProps from '../../common/PageProps'
import { APP_ROUTES } from '../../app/Routes'

const ServiceTermsPage: React.FC<PageProps> = (props) => {
    return (
        <IonContent id='serviceTermsPage' className='terms'>
            <Helmet>
                <title>Teleseat Service Terms</title>
                <meta name='description' content='Learn about Teleseat service terms' />
                <link rel='canonical' href={`https://teleseat.com${APP_ROUTES.SERVICE_TERMS}`}/>
            </Helmet>
            <IonRow className='homePage--row mt-5'>
                <IonLabel>
                    <h1 className='f-bold-40 text-color mt-4'>SERVICE TERMS</h1>
                </IonLabel>
            </IonRow>
            <IonRow className='homePage--row mt-4 mb-5'>
                <IonLabel>
                    <h4 className='f-medium-15 text-color'>Last updated February 14, 2021</h4>
                    <p className='f-15 text-color mt-5'>
                        These <strong>"Service Terms"</strong> set forth the terms upon which <strong>Teleseat Inc.</strong>, a Delaware corporation (<strong>"Teleseat"</strong>) grants to you access to and use of the Teleseat service (the <strong>"Service"</strong>) available from Teleseat through <a href='https://teleseat.com' target='_blank' rel='noopener noreferrer'>www.teleseat.com</a> (the <strong>"Website"</strong>). The term <strong>"you"</strong> (and <strong>"your"</strong>) means you, individually, or (if you are acting on behalf of your company or another organization) the entity you represent.
                    </p>
                    <h3 className='f-bold-16 text-color mt-3'>These Service Terms contain very important information regarding your rights and obligations, as well as conditions, limitations, and exclusions that might apply to you. Please read them carefully.</h3>
                    <p className='f-15 text-color mt-3'>
                        The on-line registration page, quote or order form (whether or not online) through which you have ordered the Service (the <strong>"Order"</strong>), may contain additional terms and conditions and information regarding the Service you are ordering. Such Order terms are incorporated herein and apply to your use of the Service.
                    </p>
                    <h3 className='f-bold-16 text-color mt-3'>By using the Service, establishing an account, agreeing to an Order or by clicking to accept or agree to these Service Terms when this option is made available to you, you accept and agree to be bound and abide by these Service Terms, the related Order and the other documents incorporated herein (together the "Agreement").  The Agreement is a binding, legal agreement between you and Teleseat.  Your use of the Service is conditioned on and subject to your compliance with the Agreement.  If you do not agree with the Agreement, do not use the Service.</h3>
                    <h3 className='f-bold-16 text-color mt-3'>The Agreement requires the use of arbitration on an individual basis to resolve disputes, rather than jury trials or class actions.</h3>

                    <h2 className='f-bold-18 text-color mt-4'>1. ORDERS; USERS; TERM, SUPPORT; OTHER LIMITS</h2>
                    <ul className='list'>
                        <li className='f-15 text-color'>1.1 <u>Generally.</u>  Teleseat agrees to provide you the Service as described on the Order and as further described in the then current documentation, and you agree to purchase and use such portions of the Service, all on the terms of the Agreement. Your right to use the Service commences when Teleseat notifies you that it is available for your use.</li>
                        <li className='f-15 text-color mt-3'>1.2 <u>Order.</u>  The Order specifies the transaction-specific terms applicable to your use of the portion of the Service ordered, which may include price, special payment terms, duration and whether the Service may be used with persons with email addresses under domains different from your email domains (<strong>"External Users"</strong>).  If the Order expressly identifies portions of these Services Terms that are to be superseded, then such Order will prevail over any such conflicting portions. You may not cancel the Agreement once the Order is accepted by Teleseat.</li>
                        <li className='f-15 text-color mt-3'>1.3 <u>Users.</u>   Under the Agreement, the Service may be used by you and your employees and contractors registering for the Service using email addresses with the same domains as yours.  In addition, if the Order Form indicates that the Service may be used with External Users designated by you, then such persons as you invite to use the Service (<strong>"Invitees"</strong>) may be allowed to use the Service under the Agreement.  Your personnel and the personnel of each Invitee using the Service are <strong>"End Users."</strong> Use of the Service by each Invitee and End User (together with you, each a <strong>"User"</strong>) is subject to the terms of the Agreement. You are responsible for the acts and omissions of each User, including any User’s breach of the Agreement or Teleseat’s policies related to the Service.</li>
                        <li className='f-15 text-color mt-3'>1.4 <u>Agreement Term.</u>  Subject to earlier termination as provided below, the term of the Agreement (the <strong>"Agreement Term"</strong>) commences on the date specified in the Order (or if none, the date on which Teleseat notifies you that the Service is available for your use) and continues for 1 year (60 days for a Trial License (defined below)) or such other amount of time as is specified in the Order.  Except for a Trial License, the Agreement Term automatically renews at the end of such period and each extension thereof, for additional periods of 1 year each, unless Teleseat or you request termination at least 30 days prior to the end of the then-current term.  Any extension of the Agreement Term shall be at the prices that Teleseat may quote to you at least 45 days prior to the extension date.</li>
                        <li className='f-15 text-color mt-3'>1.4 <u>Support.</u>  Teleseat will provide you with reasonable technical support in connection with the Service.  Teleseat also provides a service level agreement and credits, as outlined in the then current version of the <strong>"Service Level Terms"</strong> for the Service located at <a href='https://teleseat.com/service-level-terms' target='_blank' rel='noopener noreferrer'>https://teleseat.com/service-level-terms</a> (<strong>"Service Level Terms"</strong>).  Teleseat may amend the Service Level Terms from time to time; provided that any material reduction in protections shall not be effective until the next succeeding extension of the Agreement Term.</li>
                        <li className='f-15 text-color mt-3'>1.5 <u>Usage Terms.</u>  You hereby agree to the Usage Terms (located at <a href='https://teleseat.com/usage-terms' target='_blank' rel='noopener noreferrer'>https://teleseat.com/usage-terms</a>).  Each User will be required to agree to the Usage Terms as a condition to using the Service.</li>
                        <li className='f-15 text-color mt-3'>1.4 <u>Trial Licenses.</u>  If the Order indicates that you are receiving a "trial" "pilot" (or similar term) right to use to the Service (a <strong>"Trial License"</strong>), then the terms in these Service Terms related to the support and Service Level Terms under <strong>Section 1.5</strong> and the warranties in <strong>Section 4</strong>, do not apply to such Trial License. You may terminate the Trial License, with or without cause, at any time by ceasing use of the Service by you and all other Users. The Agreement Term for a Trial License shall not renew.</li>
                    </ul>

                    <h2 className='f-bold-18 text-color mt-4'>2. PAYMENT TERMS</h2>
                    <ul className='list'>
                        <li className='f-15 text-color'>2.1 <u>Generally.</u>  You agrees to pay Teleseat the fees and charges in the amounts and on the terms set forth in the Order.  Unless otherwise specified in the Order, all fees are payable in advance and are quoted and payable in US dollars.  You agree to pay the fees and amounts stated on the Order within 30 days after receipt of the applicable invoice (unless otherwise expressly set forth on the Order).  If you have agreed to pay by credit card, ACH or direct withdrawal, then Teleseat or its payment processor is authorized to so charge, debit or deduct the applicable card or account on or after the first day the related payment is due or when otherwise agreed.</li>
                        <li className='f-15 text-color mt-3'>2.2 <u>Overdue Amounts; Disputes.</u>  Unpaid amounts are subject to a finance charge of 1.5% per month on any outstanding balance, or the maximum permitted by law, whichever is lower, plus all expenses of collection.  If you believe that Teleseat has billed you incorrectly, you must contact Teleseat’s billing department, no later than 60 days after the closing date on the first billing statement in which the error or problem appeared, in order to receive an adjustment or credit. Otherwise, you will be deemed to have waived the right to receive such an adjustment or credit.  All fees and other amounts are non-refundable (except as otherwise expressly provided in the Agreement).</li>
                        <li className='f-15 text-color mt-3'>2.3 <u>No Taxes Included.</u>  The fees charged under the Agreement are exclusive of any applicable sales, use, value added, withholding, and other transaction-related taxes.  You agree to pay all such taxes levied or imposed by reason of the transactions under the Agreement, except for taxes based on Teleseat’s net income or related to its employees.</li>

                    </ul>

                    <h2 className='f-bold-18 text-color mt-4'>3. CONFIDENTIALITY; PROPRIETARY RIGHTS; DATA SECURITY</h2>
                    <ul className='list'>
                        <li className='f-15 text-color'>3.1 <u>Confidentiality.</u>
                            <p className='mt-3'>(a) <i>Proprietary Information Defined.</i>  Each party (the <strong>"Receiving Party"</strong>) understands that the other party (the <strong>"Disclosing Party"</strong>) has disclosed or may disclose business, technical or financial information relating to Disclosing Party or its affiliates, customers or suppliers and their respective businesses (<strong>"Proprietary Information"</strong>).  Proprietary Information of Teleseat includes non-public information regarding the Service, including the features, structure, functionality and performance of the Service.  Your Proprietary Information includes non-public data that you or Users provide to Teleseat to enable the provisioning of the Service and the content sent or transmitted by a User or displayed or uploaded by a User when using the Service, including all recordings of sessions in the Service (<strong>"Content"</strong>) that you or any User provides to Teleseat, including personal information.</p>
                            <p className='mt-3'>(b) <i>Protection of Proprietary Information.</i> The Receiving Party agrees: (i) to take reasonable precautions to protect such Proprietary Information of the Disclosing Party, and (ii) not to use (except in performance of the Service or as otherwise permitted herein) or divulge to any third person any such Proprietary Information.  Each party will only disclose the Proprietary Information of the other to such of its employees and contractors who are required to have the information in connection with the Agreement and who have signed a confidentiality agreement at least as protective as this Section <strong>3.1</strong>.  The Disclosing Party agrees that the foregoing shall not apply to any information that the Receiving Party can document (A) is or becomes generally available to the public; (B) was in its possession or known by it prior to receipt from the Disclosing Party, (C) was independently developed by persons who did not have access to any Proprietary Information of the Disclosing Party; or (D) was rightfully disclosed to it without restriction by a third party.  In addition, Teleseat may use and disclose your Proprietary Information as set forth in the Privacy Policy.  This Section shall not preclude disclosure of Proprietary Information to the extent required to be disclosed by applicable law; provided that the Receiving Party will provide prompt notice thereof to enable the Disclosing Party to seek a protective order or otherwise prevent such disclosure.   Following the termination of the Agreement, each party will return or destroy, within 30 days of termination, all copies of the Proprietary Information disclosed by the other party, except for a limited number of electronic backup copies of such information as are automatically created and retained by the receiver’s standard backup processes and systems for purposes of disaster recovery.</p>
                        </li>
                        <li className='f-15 text-color mt-3'>3.2 <u>Feedback.</u>  If you or any User notifies Teleseat of any bugs or errors in the Service or otherwise provides suggestions, comments, and other feedback (individually and collectively, <strong>"Feedback"</strong>), then you grant Teleseat a perpetual, irrevocable, royalty-free, sublicensable, and transferable license to use and exploit the Feedback.</li>
                        <li className='f-15 text-color mt-3'>3.3 <u>Privacy.</u>  You agree to the Teleseat <strong>"Privacy Policy"</strong> located at <a href='https://teleseat.com/privacy' target='_blank' rel='noopener noreferrer'>https://teleseat.com/privacy</a> (the <strong>"Privacy Policy"</strong>). Teleseat may amend the Privacy Policy from time to time, as set forth therein, provided that any material reduction in protections shall not be effective until the next succeeding extension of the Agreement Term.  You will be deemed to have agreed to such amendments as set forth in the Privacy Policy.  Teleseat may access the Content and your personal information, in connection with monitoring the Service for technical performance, to respond to service or technical problems, to plan for service upgrades or enhancements, or as otherwise stated in the Privacy Policy. Teleseat will not otherwise monitor, edit, or disclose the Content, without your prior permission.</li>
                        <li className='f-15 text-color mt-3'>3.4 <u>Reservation of Rights.</u>  Each User’s right to use the Service will be limited to the rights expressly granted in <strong>Section 1</strong>.  Teleseat reserves all other right, title, and interest therein, including all intellectual property rights. You acknowledge that nothing in the Agreement transfers to you ownership of any of Teleseat’s intellectual property rights.</li>
                        <li className='f-15 text-color mt-3'>3.5 <u>Usage Information.</u>  Notwithstanding the other terms of the Agreement, Teleseat may collect and use information related to the way you and other Users use the Service, but expressly excluding the substance of any User communications or materials  (<strong>"Usage Information"</strong>). Teleseat may use Usage Information to support, test, develop, improve and enhance its products and services and the products and services of its affiliates.  Teleseat also may use and disclose, for any legitimate business purposes, Usage Information that has been de-identified, anonymized, and/or aggregated.</li>
                        <li className='f-15 text-color mt-3'>3.6 <u>Content Obligations.</u>  Teleseat will maintain reasonable physical and technical safeguards to prevent unauthorized disclosure of or access to Content, in accordance with industry standards. Teleseat will notify you if it becomes aware of unauthorized access to Content. Teleseat will not access, view or process Content except (a) as provided for in the Agreement and in the Privacy Policy; (b) as you may authorize or instruct; (c) as required to perform its obligations under the Agreement; or (d) as required by applicable law. Teleseat has no other obligations with respect to Content.</li>
                    </ul>

                    <h2 className='f-bold-18 text-color mt-4'>4. WARRANTY AND DISCLAIMER</h2>
                    <p className='f-15 text-color mt-3'>Teleseat shall provide the Service consistent with prevailing industry standards, maintain the Service in a manner which minimizes errors and interruptions in the Service and not materially decrease the overall functionality of the Service during the then current Agreement Term.  The Service may be temporarily unavailable for scheduled maintenance or for unscheduled emergency maintenance, either by Teleseat or by third-party providers, or because of other causes beyond Teleseat’s reasonable control, but Teleseat shall provide prompt notice in writing or by e-mail of any scheduled service disruption and take all reasonable efforts to reinstate the Service and minimize the impact of any downtime.  If Teleseat breaches the foregoing warranties, then, its sole obligation and your sole remedy, shall be for Teleseat, at its election, to either correct such breach within 30 days or terminate the Agreement and refund to you any prepaid fees allocable to the remainder of the Agreement Term.  <strong className='uppercase'>Except as set out in the Agreement, (a) Teleseat does not warrant that the Service will be uninterrupted or error free, nor does it make any warranty as to the results that may be obtained from use of the Service, and (b) the Service is provided "as is" and Teleseat disclaims all warranties, express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, satisfactory quality, accuracy of information, and noninfringement.</strong></p>

                    <h2 className='f-bold-18 text-color mt-4'>5. INDEMNITY</h2>
                    <p className='f-15 text-color mt-3'>You agree to indemnify, defend and hold harmless Teleseat, its affiliates, officers, directors, employees, consultants and agents from any and all third party claims, liability, damages and/or costs (including attorneys' fees) arising from your and each User's use of the Service, violation of the Agreement (including the Usage Terms) or the infringement or violation, of any intellectual property or other right of any person or entity or applicable law.</p>

                    <h2 className='f-bold-18 text-color mt-4'>6. TERMINATION</h2>
                    <ul className='list'>
                        <li className='f-15 text-color'>6.1 <u>Termination for Cause.</u>  In addition to any other remedies it may have, either party may also terminate the Agreement upon notice, if the other party materially breaches the Agreement and fails to cure such breach within 30 days (10 days in the case of payment breach) of notice of such breach.</li>
                        <li className='f-15 text-color mt-3'>6.2 <u>Effect of Termination.</u>  Upon the termination or expiration of the Agreement for any reason, (a) the Agreement Term and each User’s right to access the Service and all licenses granted hereunder immediately terminate; and (b) Teleseat and its licensors shall have no obligation to maintain any Content stored in a terminated account or to forward or make Content available to you or other Users. If Teleseat terminates the Agreement due to your breach, then, in addition to Teleseat’s other remedies, you shall pay all amounts under the Agreement which would have been payable through the end of the Agreement Term.  The expiration or termination of the Agreement will not (i) affect your obligation to pay all amounts due to Teleseat accrued prior to termination (or, where applicable, after termination), nor (ii) entitle you to reimbursement or refund of any amounts already paid to Teleseat. In addition, <strong>Sections 2, 3, 4, 5, 6, 7 and 8</strong> will survive the expiration or termination of the Agreement.</li>
                    </ul>

                    <h2 className='f-bold-18 text-color mt-4'>7. LIMITATION OF LIABILITY</h2>
                    <p className='f-15 text-color mt-3'><strong className='uppercase'>Notwithstanding anything to the contrary, except for breach of or liability under Section 3.1 or 5,  fraud or bodily injury of a person (collectively, "Exclusions"), neither party, nor its officers, affiliates, representatives, contractors or employees shall be responsible or liable with respect to the Service or any other subject matter of the Agreement under any contract, negligence, strict liability or other theory: (a) for error or interruption of use or for loss or inaccuracy or corruption of data or cost of procurement of substitute goods, services or technology, or loss of business; (b) for any indirect, exemplary, incidental, special or consequential damages; or (c) for any matter beyond such party’s reasonable control. For all other claims except for Exclusions and your obligation to pay fees hereunder, neither party shall be liable under the Agreement for any amounts that exceed the fees paid by you to Teleseat for the Service in the 12 months prior to the act that gave rise to the liability, in each case, whether or not the party has been advised of the possibility of such damages.</strong></p>

                    <h2 className='f-bold-18 text-color mt-4'>8. MISCELLANEOUS</h2>
                    <ul className='list'>
                        <li className='f-15 text-color'>8.1 <u>Severability.</u>  If any provision of the Agreement is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that the Agreement will otherwise remain in full force and effect and enforceable.</li>
                        <li className='f-15 text-color mt-3'>8.2 <u>Assignment.</u>  The Agreement is not assignable, transferable or sublicensable by you, including by operation of law, except with Teleseat’s prior written consent.  Teleseat may transfer and assign any of its rights and obligations under the Agreement without consent.  Any attempted assignment in violation of the foregoing is void.</li>
                        <li className='f-15 text-color mt-3'>8.3 <u>Entire Agreement.</u>  The Agreement constitutes the entire, final, and complete agreement between the parties with respect to the subject matter thereof.  The preprinted terms and conditions contained in any purchase order, order acceptance or other document submitted by either party will be of no effect, notwithstanding any contrary provisions in such terms.  Except as expressly provided herein, no modification of or amendment to the Agreement, nor any waiver of any rights under the Agreement, shall be effective unless in writing signed by both parties.</li>
                        <li className='f-15 text-color mt-3'>8.4 <u>No Agency.</u>  No agency, partnership, joint venture, or employment relationship is created as a result of the Agreement and you do not have any authority of any kind to bind Teleseat in any respect whatsoever.</li>
                        <li className='f-15 text-color mt-3'>8.5 <u>Force Majeure.</u>  Nonperformance of either party shall be excused to the extent that performance is rendered impossible by strike, fire, flood, governmental acts, orders or restrictions, or any other reason where failure to perform is beyond the control of, and not caused by the negligence of, the non-performing party.</li>
                        <li className='f-15 text-color mt-3'>8.6 <u>Export Controls.</u>  You may not remove or export from the United States or allow the export or re-export of the Service or anything related thereto, or any direct product thereof in violation of any restrictions, laws or regulations of the United States Department of Commerce, the United States Department of Treasury Office of Foreign Assets Control, or any other United States or foreign agency or authority.</li>
                        <li className='f-15 text-color mt-3'>8.7 <u>Notices.</u>  All notices under the Agreement shall be in writing and will be deemed to have been duly given when received, if personally delivered; when receipt is electronically confirmed, if transmitted by facsimile or e-mail; the day after it is sent, if sent for next day delivery by recognized overnight delivery service; and upon receipt, if sent by certified or registered mail, return receipt requested.  Such notices shall be sent to the address indicated below, in the case of Teleseat, or, for you as specified in the Order or your account registration, or to such other address as the addressee will have last furnished in writing to the addressor.
                            <p className='pl-4 mt-3'>
                                Teleseat Inc.<br />
                                4125 Hopyard Rd, Suite 225<br />
                                Pleasanton, CA 94588<br />
                                Telephone: <a href='tel:9254330377'>(925) 433-0377</a><br />
                                e-mail: <a href='mailto:sales@teleseat.com'>sales@teleseat.com</a><br />
                            </p>
                        </li>
                        <li className='f-15 text-color mt-3'>8.8 <u>Governing Law; Jurisdiction.  Prevailing Party.</u>  The Agreement shall be governed by the laws of the State of California, without regard to conflict of laws provisions. Subject to <strong>Section 8.9</strong>, any suit under the Agreement (other than to enforce a judgment or award) will be brought in the federal or state courts in the districts which include Pleasanton, California.  You agree and submit to the personal jurisdiction and venue of such courts.  In any action or proceeding to enforce rights under the Agreement, the prevailing party will be entitled to recover costs, including arbitration and expert witness fees, and attorneys' fees.</li>
                        <li className='f-15 text-color mt-3'>8.9 <u>Arbitration; Class Action Waiver.</u>  Any dispute, claim or controversy arising out of or relating to the Agreement or the breach, termination, enforcement, interpretation or validity thereof, including the determination of the scope or applicability of this agreement to arbitrate, shall be determined by arbitration in Pleasanton, California before one arbitrator.  The arbitrator will be chosen from a panel of arbitrators with substantive knowledge relevant to the subject matter of the dispute.  The arbitration shall be administered by JAMS pursuant to its Comprehensive Arbitration Rules and Procedures and in accordance with the Expedited Procedures in those Rules. Judgment on the award may be entered in any court having jurisdiction. This Section shall not preclude parties from seeking provisional remedies, including injunctive relief, from a court of appropriate jurisdiction.  Notwithstanding any rules of JAMS to the contrary, any claims shall be adjudicated on an individual basis only, and <strong>you hereby waive any right to bring any claim as a representative of a proposed class, on an aggregated or mass basis, or as a private attorney general, or to consolidate arbitration proceedings without the consent of all parties thereto.</strong></li>
                        <li className='f-15 text-color mt-3'>8.10 <u>Publicity.</u>  The parties shall work together in good faith to issue at least one mutually agreed upon press release within 90 days of the start of the Agreement Term.  Teleseat may include your name and logo on lists of customers of the Service, including the Website.  You also agree to reasonably cooperate with Teleseat to serve as a reference account upon request.</li>
                        <li className='f-15 text-color mt-3'>8.11 <u>Other Interpretive Provisions.</u>  References in the Service Terms to <strong>"Sections"</strong> are to sections herein unless otherwise indicated.  The words <strong>"include"</strong> and <strong>"including"</strong> and words of similar import when used in the Agreement shall not be construed to be limiting or exclusive.  For purposes of the Agreement, the word <strong>"will"</strong> shall be equivalent in meaning to the word <strong>"shall,"</strong> both of which describe an act or forbearance which is mandatory under the Agreement.  Except as provided in a particular context, the word <strong>"or"</strong> when used in the Agreement may mean each as well as all alternatives.  Headings in the Agreement are for convenience of reference only and are not part of the substance hereof.</li>
                    </ul>
                </IonLabel>
            </IonRow>
        </IonContent>
    )
}

export default ServiceTermsPage